id: A254442A3
title: The Swift Fulfilment of All Wishes—Offering the Flag of Windhorse
type: translation
pechas:
- I00147612
- I124B3A12
- I444D58D8
- I21B171DD
- IDC783D93
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:09:31.397621
  last_modified_at: 2023-01-04 13:09:31.397627
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I00147612/247C: C6CE
  I124B3A12/CC8A: C6CE
  I444D58D8/78EC: C6CE
  I21B171DD/A3AD: C6CE
  IDC783D93/4129: C6CE
